### ISSUE TITLE
NoSuchMethodError in Intelij 2017.1

### ISSUE THREAD

**Issue by bvoss** [shiraji/databinding-support#35]
Since I have updated to InteliJ 2017.1, I got the following error:

> com.intellij.util.containers.UtilKt.isNullOrEmpty(Ljava/util/List;)Z
java.lang.NoSuchMethodError: com.intellij.util.containers.UtilKt.isNullOrEmpty(Ljava/util/List;)Z
	at com.github.shiraji.databindinglayout.linemaker.LayoutNavigationLineMarkerProvider.getLineMarkerInfo(LayoutNavigationLineMarkerProvider.kt:26)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:186)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by shiraji** [comment]
Thanks for your report. I will check this.

**Comment by shiraji** [comment]
Could you try uninstall/install this pluin? Because I cannot repoduce thie error using Intellij 2017.1

**Comment by bvoss** [comment]
Thank you for the fast response!

Still the same after reinstall. :-/

**Comment by shiraji** [comment]
Which version of Kotlin plugin do you install to the IDE?

Some version has this bug https://youtrack.jetbrains.com/issue/KT-15786

**Comment by bvoss** [comment]
My Kotlin version is: 1.1.1-release-IJ2017.1-1

Maybe its related to the bug you mentioned, but as I understood it, it should be fixed in 1.1.1. What do you think?

**Comment by shiraji** [comment]
The issue status is fix but not verified yet. Meaning it's not released the fix yet.  I'm using `1.1.2-dev-504`. The plugin works fine with Intellij 2017.1. You may need to wait until they fix it.

**Comment by bvoss** [comment]
OK, thank you very much.

I'll close this issue and reopen it, if necessary.

**Comment by shiraji** [comment]
I will fix this problem since Kotlin 1.1.2 also has the same problem.

**Comment by shiraji** [comment]
Release with v1.1.0. Could you verify that?
