### ISSUE TITLE
AS 2.3 on preview error

### ISSUE THREAD

**Issue by kimukou** [shiraji/databinding-support#45]
using 1.0.9 plugin

Although the reproduction method is unknown, since it was displayed as error of databinding-support in the title part

I will report it just in case (Do you recover when I re-do Gradle Sync?)

```
Duplicate key com.android.tools.idea.res.LayoutDataBindingInfo@7f77a711
java.lang.IllegalStateException: Duplicate key com.android.tools.idea.res.LayoutDataBindingInfo@7f77a711
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.android.tools.idea.res.ResourceFolderRepository.getDataBindingResourceFiles(ResourceFolderRepository.java:600)
	at com.android.tools.idea.res.MultiResourceRepository.getDataBindingResourceFiles(MultiResourceRepository.java:133)
	at com.android.tools.idea.databinding.DataBindingClassFinder.findClass(DataBindingClassFinder.java:48)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:122)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiManager.findClassWithCache(GroovyPsiManager.java:137)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GrLiteralClassType.resolve(GrLiteralClassType.java:156)
	at com.intellij.psi.util.TypeConversionUtil$6.visitClassType(TypeConversionUtil.java:1320)
	at com.intellij.psi.util.TypeConversionUtil$6.visitClassType(TypeConversionUtil.java:1311)
	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:236)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1311)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1305)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.GroovyResolverProcessor.eraseTypes(GroovyResolverProcessor.java:363)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.GroovyResolverProcessor.<init>(GroovyResolverProcessor.java:101)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.GroovyResolverProcessorImpl.<init>(GroovyResolverProcessorImpl.java:42)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.GroovyResolverProcessorBuilder.build(GroovyResolverProcessorBuilder.java:41)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl._resolve(GrReferenceExpressionImpl.java:513)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.doPolyResolve(GrReferenceExpressionImpl.java:483)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.access$000(GrReferenceExpressionImpl.java:66)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.resolve(GrReferenceExpressionImpl.java:205)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.resolve(GrReferenceExpressionImpl.java:201)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext$1.multiResolve(InferenceContext.java:64)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.multiResolve(GrReferenceExpressionImpl.java:601)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.advancedResolve(GrReferenceElement.java:44)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.resolve(GrReferenceElement.java:39)
	at org.jetbrains.plugins.groovy.lang.psi.impl.PsiImplUtil.getRuntimeQualifier(PsiImplUtil.java:289)
	at org.jetbrains.plugins.groovy.lang.psi.impl.PsiImplUtil.getQualifierType(PsiImplUtil.java:977)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.GroovyResolverProcessor.<init>(GroovyResolverProcessor.java:97)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.GroovyResolverProcessorImpl.<init>(GroovyResolverProcessorImpl.java:42)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.GroovyResolverProcessorBuilder.build(GroovyResolverProcessorBuilder.java:41)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl._resolve(GrReferenceExpressionImpl.java:513)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.doPolyResolve(GrReferenceExpressionImpl.java:483)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.access$000(GrReferenceExpressionImpl.java:66)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.resolve(GrReferenceExpressionImpl.java:205)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.resolve(GrReferenceExpressionImpl.java:201)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext$1.multiResolve(InferenceContext.java:64)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.multiResolve(GrReferenceExpressionImpl.java:601)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.advancedResolve(GrReferenceElement.java:44)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.resolve(GrReferenceElement.java:39)
	at org.jetbrains.plugins.groovy.annotator.GroovyAnnotator.checkFinalFieldAccess(GroovyAnnotator.java:337)
	at org.jetbrains.plugins.groovy.annotator.GroovyAnnotator.visitReferenceExpression(GroovyAnnotator.java:308)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.accept(GrReferenceExpressionImpl.java:104)
	at org.jetbrains.plugins.groovy.annotator.GrAnnotatorImpl.annotate(GrAnnotatorImpl.java:51)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:334)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$2(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:293)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$3(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:175)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:363)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:174)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$3(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1029)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by kimukou** [comment]
Perhaps during layout copy using data-binding
Hoge.xml
=>
Hoge_.xml
I feel like I've done it
(Maybe google bug)

Hoge_a.xml
There was no problem if you changed the file name.

Just saying bugs in plugin is troublesome (sweat

**Comment by shiraji** [comment]
Let's see if I can reproduce this one. Thanks for reporting!

**Comment by shiraji** [comment]
I reproduce this issue but I don't think this is the problem with this plugin. 

![2017-04-28 14 32 44](https://cloud.githubusercontent.com/assets/3675458/25515446/9c72489c-2c1f-11e7-8a51-a5c91132870f.png)

![2017-04-28 14 32 57](https://cloud.githubusercontent.com/assets/3675458/25515448/9eb08af6-2c1f-11e7-853c-f8785835a657.png)

If I click disable plugin, AS tries to disable `Android Support` not `Databinding support` plugin.
